# Generated by Django 5.1.1 on 2024-10-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('orders', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cake',
            fields=[
            ],
            options={
                'ordering': ['orders'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('proxy.cafe',),
        ),
        migrations.CreateModel(
            name='ColdDrink',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('proxy.cafe',),
        ),
    ]
